import { Company } from "@/types";

export const mockCompanies: Company[] = [
  {
    id: "1",
    name: "Stripe",
    website: "https://stripe.com",
    description: "Online payment processing for internet businesses",
    stage: "Series H",
    industry: "Fintech",
    location: "San Francisco, CA",
    founded: 2010,
    employees: "7,000+",
    funding: "$2.9B",
    tags: ["payments", "saas", "b2b"],
  },
  {
    id: "2",
    name: "OpenAI",
    website: "https://openai.com",
    description: "AI research and deployment company",
    stage: "Series Unknown",
    industry: "AI/ML",
    location: "San Francisco, CA",
    founded: 2015,
    employees: "700+",
    funding: "$11.3B",
    tags: ["ai", "ml", "research"],
  },
  {
    id: "3",
    name: "Notion",
    website: "https://notion.so",
    description: "All-in-one workspace for notes, docs, and collaboration",
    stage: "Series C",
    industry: "Productivity",
    location: "San Francisco, CA",
    founded: 2016,
    employees: "300+",
    funding: "$343M",
    tags: ["productivity", "saas", "collaboration"],
  },
  {
    id: "4",
    name: "Figma",
    website: "https://figma.com",
    description: "Collaborative interface design tool",
    stage: "Acquired",
    industry: "Design",
    location: "San Francisco, CA",
    founded: 2012,
    employees: "1,200+",
    funding: "$333M",
    tags: ["design", "saas", "collaboration"],
  },
  {
    id: "5",
    name: "Vercel",
    website: "https://vercel.com",
    description: "Platform for frontend developers",
    stage: "Series D",
    industry: "Developer Tools",
    location: "San Francisco, CA",
    founded: 2015,
    employees: "400+",
    funding: "$313M",
    tags: ["developer-tools", "saas", "infrastructure"],
  },
  {
    id: "6",
    name: "Anthropic",
    website: "https://anthropic.com",
    description: "AI safety and research company",
    stage: "Series C",
    industry: "AI/ML",
    location: "San Francisco, CA",
    founded: 2021,
    employees: "200+",
    funding: "$4B",
    tags: ["ai", "safety", "research"],
  },
  {
    id: "7",
    name: "Linear",
    website: "https://linear.app",
    description: "Issue tracking and project management for software teams",
    stage: "Series B",
    industry: "Developer Tools",
    location: "San Francisco, CA",
    founded: 2019,
    employees: "100+",
    funding: "$35M",
    tags: ["developer-tools", "saas", "productivity"],
  },
  {
    id: "8",
    name: "Ramp",
    website: "https://ramp.com",
    description: "Corporate cards and expense management",
    stage: "Series C",
    industry: "Fintech",
    location: "New York, NY",
    founded: 2019,
    employees: "500+",
    funding: "$1.1B",
    tags: ["fintech", "saas", "b2b"],
  },
  {
    id: "9",
    name: "Retool",
    website: "https://retool.com",
    description: "Build internal tools fast",
    stage: "Series C",
    industry: "Developer Tools",
    location: "San Francisco, CA",
    founded: 2017,
    employees: "300+",
    funding: "$141M",
    tags: ["developer-tools", "saas", "low-code"],
  },
  {
    id: "10",
    name: "Brex",
    website: "https://brex.com",
    description: "Financial services and corporate credit cards",
    stage: "Series D",
    industry: "Fintech",
    location: "San Francisco, CA",
    founded: 2017,
    employees: "1,200+",
    funding: "$1.2B",
    tags: ["fintech", "saas", "b2b"],
  },
];
